/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PdfViewer {
        /**
          * Add class to iframe
         */
        "customClass"?: string;
        /**
          * Download url of PDF
         */
        "downloadUrl": string;
        /**
          * Render custom error component
         */
        "errorComponent"?: () => any;
        /**
          * Render custom loading component
         */
        "loadingComponent"?: () => any;
    }
}
declare global {
    interface HTMLPdfViewerElement extends Components.PdfViewer, HTMLStencilElement {
    }
    var HTMLPdfViewerElement: {
        prototype: HTMLPdfViewerElement;
        new (): HTMLPdfViewerElement;
    };
    interface HTMLElementTagNameMap {
        "pdf-viewer": HTMLPdfViewerElement;
    }
}
declare namespace LocalJSX {
    interface PdfViewer {
        /**
          * Add class to iframe
         */
        "customClass"?: string;
        /**
          * Download url of PDF
         */
        "downloadUrl"?: string;
        /**
          * Render custom error component
         */
        "errorComponent"?: () => any;
        /**
          * Render custom loading component
         */
        "loadingComponent"?: () => any;
    }
    interface IntrinsicElements {
        "pdf-viewer": PdfViewer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pdf-viewer": LocalJSX.PdfViewer & JSXBase.HTMLAttributes<HTMLPdfViewerElement>;
        }
    }
}
